---
- name: Prepare build
  hosts: build
  become: yes

  tasks:
   - name: Ensure mvn package is present
     apt:
      name: maven
      state: present

   - name: Ensure git package is	present
     apt:
      name: git
      state: present

- name: Build
  hosts: build
  become: yes

  tasks:
   - name: Clone app from git
     git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello'
      dest: /home/user/build/

   - name: Build app
     shell: mvn package chdir="/home/user/build/"

   - name: Copy app from build
     synchronize:
      src: /home/user/build/target/hello-1.0.war
      dest: /home/user/
      mode: pull
     delegate_to: 127.0.0.1

- name: Prod
  hosts: prod
  become: yes

  tasks:
   - name: Install OpenJDK
     apt:
      name: openjdk-11-jre-headless

   - name: Install Tomcat
     apt:
      name: tomcat9

   - name: Enable Tomcat startup 
      systemd:
      name: tomcat
      enabled: yes
      state: restarted
      become: true

   - name: Copy app to prod
     copy:
      src: /home/user/hello-1.0.war
      dest: /var/lib/tomcat9/webapps

