---
- name: Prepare build
  hosts: build
  become: yes

  tasks:
   - name: Ensure mvn package is present
     apt:
      name: maven
      state: present

   - name: Ensure git package is	present
     apt:
      name: git
      state: present

- name: Build
  hosts: build
  become: yes

  tasks:
   - name: Clone app from git
     git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello'
      dest: /home/user/build/

   - name: Build app
     shell: mvn package chdir="/home/user/build/"

   - name: Copy app from build to prod
     synchronize:
      src: /home/user/build/target/hello-1.0.war
      dest: /home/user/
      mode: pull
     delegate_to: "10.8.5.65"

- name: Prod
  hosts: prod
  become: yes

  tasks:
   - name: Ensure tomcat package is present
     apt:
      name: tomcat
      state: present

  tasks:
    - name: Ensure tomcat service is started
      service:
       name: tomcat
       state: started

    - name: Ensure copy app
      copy:
       src: /home/user/hello-1.0.war
       dest: /opt/tomcat/webapps

